sudo: required
language: python
python:
  - '3.6'
dist: trusty
services:
  - docker
env:
  global:
    - DJANGO_VERSION=2.0
    - TRAVIS=True
    - TEST_CMD=docker exec -it molecular-server test.sh
install:
  - curl -sSL "https://get.docker.com/gpg" | sudo -E apt-key add -
  - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
before_script:
  - docker-compose -f docker-compose.yml up -d
  - docker ps
script:
- ${TEST_CMD}
notifications:
  email:
    - we.veggieavocado@gmail.com
    - ppark9553@gmail.com
  on_success: always
  on_failure: always
