sudo: required
language: python
python:
- '3.6'
services:
  - docker
env:
  global:
  - DJANGO_VERSION=2.0
  - TRAVIS=True
  - TEST_CMD=docker exec -it molecular-server test.sh
install:
- apt-get update
- apt-get install docker.io
- curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
- chmod +x /usr/local/bin/docker-compose
before_script:
- docker-compose up -d
- docker ps
script:
- ${TEST_CMD}
notifications:
  email:
  - keystQuant@gmail.com
  - ppark9553@gmail.com
  on_success: always
  on_failure: always
