sudo: required
language: python
python:
  - '3.6'
dist: trusty
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - DJANGO_VERSION=2.0
    - TRAVIS=True
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements.txt
before_script:
  - docker run --name molecular-cache -d redis redis-server --requirepass molecularredispassword --appendonly yes
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python -m pytest -n 3 --cov-config .coveragerc --cov=. -v
notifications:
  email:
    - we.veggieavocado@gmail.com
    - ppark9553@gmail.com
  on_success: always
  on_failure: always
