version: "3"

services:
  nginx:
    build: ./config/nginx
    container_name: molecular-nginx
    depends_on:
      - web
    links:
      - web:web
    ports:
      - 3000:3000
    networks:
      - molecular
    restart: unless-stopped

  web:
    build: .
    container_name: molecular-django
    environment:
      - DOCKER_CONTAINER=True
    depends_on:
      - redis
      - celery
    links:
      - redis:redis
    networks:
      - molecular
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Celerydocker
    container_name: molecular-celery
    environment:
      - DOCKER_CONTAINER=True
    depends_on:
      - rabbit
    links:
      - rabbit:rabbit
    networks:
      - molecular
    restart: unless-stopped

  celerybeat:
    build:
      context: .
      dockerfile: Beatdocker
    container_name: molecular-celerybeat
    environment:
      - DOCKER_CONTAINER=True
    depends_on:
      - rabbit
    links:
      - rabbit:rabbit
    networks:
      - molecular
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: Flowerdocker
    container_name: molecular-flower
    ports:
      - 5555:5555
    environment:
      - DOCKER_CONTAINER=True
    depends_on:
      - celery
      - celerybeat
    networks:
      - molecular
    restart: unless-stopped

  redis:
    image: redis
    container_name: molecular-redis
    command: redis-server --requirepass molecularredispassword --appendonly yes
    ports:
      - 6379:6379
    networks:
      - molecular
    volumes:
      - cache_data:/data
    restart: unless-stopped

  rabbit:
    image: rabbitmq:3-management
    container_name: molecular-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=molecularuser
      - RABBITMQ_DEFAULT_PASS=molecularrabbitmqpassword
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - molecular
    restart: unless-stopped

networks:
  molecular:
    driver: bridge

volumes:
  cache_data:
